Fix compile errors with clang 8
Summary:
Fix issues causing:

* hostcopy.hpp:79:55: error: extra ';' after member function definition [-Werror,-Wextra-semi]

Ref T34131.

Reviewers: #popart, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, evan

Reviewed By: #popart, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, evan

Maniphest Tasks: T34131

Differential Revision: https://phabricator.sourcevertex.net/D44160