Add missing includes to fix gcc10 build
Summary:
Fixes errors like:

  In file included from ../willow/src/intervals.cpp:2:
  ../willow/include/popart/intervals.hpp:19:42: error: 'int64_t' was not declared in this scope
     19 | getDecreasingIntervals(const std::vector<int64_t> &floorHeights);
        |                                          ^~~~~~~

Ref T36072.

Reviewers: #popart, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, jamesn, matthewha

Reviewed By: #popart, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, matthewha

Maniphest Tasks: T36072

Differential Revision: https://phabricator.sourcevertex.net/D45227