sourceTensors of IPU copy ops not being updated when IpuCopyOp::disconnectInTensor() is called
Summary:
`ContiguateIpuCopyIndicesPattern::matches()` has the condition:
```
    if (copyOp->getSourceTensors().size() != 1) {
      return false;
    }
```
but the logic to update the sourceTensors state for IpuCopyOps when disconnecting and reconnecting the input wasn't working, causing it to hit the above condition when there was only one source tensor.

Fixes T12405

Test Plan:
All regression tests pass.

Failing test:
```
cd internal_sdk_tests
pytest synthetic_benchmarks/popart/transformer/test_popart_transformer_synthetic.py::TestPopARTTransformerSyntheticBenchmarks::test_transformer_inference_2_8_64_128_512_8_1024_16shard_pipelined
```
with exception
```
popart_core.popart_exception: ILE: IpuCopy Op(ai.graphcore.IpuCopy:1, outputs=[input/3_c14]) is not contiguous. It copies from IPU 12 to IPU 14. Failed to contiguate all IpuCopyOps
```

now passes

Reviewers: jamesn, george, matthewha, simonl, stephenm

Reviewed By: stephenm

Maniphest Tasks: T12405

Differential Revision: https://phabricator.sourcevertex.net/D16477