Revert 'Use poplar SDK libs' config files and make libpvti public in popart'
Summary: This reverts commit c93ead10fe121d239a89ca111c9a39185665bc49.

Caused:
```
Traceback (most recent call last):
  File "gen_supported_ops.py", line 15, in <module>
    import popart
  File "/home/buildslave/workdir/buildslave/onnx_ubuntu_18_04/src/build/build/popart/popart/python/popart/__init__.py", line 21, in <module>
    from popart_opset11 import *
ModuleNotFoundError: No module named 'popart_opset11'
```

Test Plan: revert-hammer

Reviewers:

Subscribers: