Fix compile errors with clang 8
Summary:
Fix issues causing:

* willow/src/onnxpasses/patterntarget.hpp:35:67: error: extra ';' after member function definition [-Werror,-Wextra-semi]
* delete called on 'popart::onnxpasses::ConstFoldOp' that is abstract but has non-virtual destructor [-Werror,-Wdelete-abstract-non-virtual-dtor] (and similar)

Ref T34131.

Reviewers: #popart, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, shirazb

Reviewed By: #popart, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, shirazb

Maniphest Tasks: T34131

Differential Revision: https://phabricator.sourcevertex.net/D42551