popart.ir: prevent fallback of tensor __iter__ and __contains__ to __getitem__ which produces unhelpful errors
Summary:
Prevent use of tensor's default methods `__iter__` and `__contains__` which call `__getitem__` and produces unhelpful errors.

For example before:
```
import popart.ir as pir
with pir.Ir().main_graph():
    x = pir.variable(0)
    l = []
    l += x
```

Error:
```
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File ".../popart/ir/tensor.py", line 138, in __len__
    return self.shape[0]
IndexError: tuple index out of range
```

Example 2:
```
import popart.ir as pir
with pir.Ir().main_graph():
    x = pir.variable(0)
    1 in x
```

Error:
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File ".../popart/ir/tensor.py", line 274, in __getitem__
    out = ops.slice(self, start, stop, step)
  File ".../popart/ir/context.py", line 408, in wrapper
    result = func(*args, **kwargs)
  File ".../popart/ir/ops/slice.py", line 71, in slice
    settings=settings,
  File ".../popart/ir/context.py", line 158, in wrapper
    op = fn(*args, **kwargs)
popart_core.popart_exception: Invalid input shape in BaseSliceOp::getSlices. The input shape has rank 0, but axis = 0. axis must be less than the input shape's rank. This error is for Op 100 (ai.onnx.Slice:11).
```

The errors are because the default `__iter__` and `__contains__`  methods will call `__getitem__` if its defined by the user. This behaviour isn't well documented and took a while to work out - see https://stackoverflow.com/a/59294875/1110328.

New error 1:
```
TypeError: 'Variable' object is not iterable
```

New error 2:
```
TypeError: 'Variable' object is not a container
```

Reviewers: #popart, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, shirazb, oskarb

Reviewed By: #popart, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, shirazb

Maniphest Tasks: T41460

Differential Revision: https://phabricator.sourcevertex.net/D58368