Add how to execute imported model to PopART documentation
Summary:
PopART documentation include how to import a graph but not how to execute the imported graph. There are some pitfalls that a beginner might encounter. Hence, it would be good to add content on how to execute the imported graph.

A simple script on how to add inputs and run `PyStepIO` has been added. I also have a more complicated script, which contains building dataset and infeed pipeline as well. (Need opinion on which to include)

Relevant content has also been added to the doc. However, there are some contents overlapping with the section ["Executing graphs" ](https://docs.graphcore.ai/projects/popart-user-guide/en/latest/executing.html). I'm open to suggestions on how to make it informative yet not redundant.

Test Plan:
Running  `python -m pytest tests/test_examples.py` gives the following error message.

```
========================================================================================================================================================= FAILURES =========================================================================================================================================================
_________________________________________________________________________________________________________________________________ TestPythonDocExamples.test_documentation_import_session __________________________________________________________________________________________________________________________________

self = <test_examples.TestPythonDocExamples testMethod=test_documentation_import_session>

    def test_documentation_import_session(self):
        """Test the import session example"""
        filename = "importing_session.py"
>       self.run_python(filename, self.base_path)

tests/test_examples.py:60:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/test_examples.py:46: in run_python
    self.run_command(cmd, self.cwd, timeout_secs)
tests/test_examples.py:40: in run_command
    Output of failed command:\n{combined_output}""")
E   AssertionError: The following command failed: /localdata/yis/workspace/SDK/poplar_sdk-ubuntu_18_04-2.4.0+840-3f0821ff57/2.4.0+840_poptorch/bin/python /localdata/yis/workspace/poplar/popart/docs/user_guide/files/importing_session.py
E
E                   Working path: /localdata/yis/workspace/poplar/popart/docs/user_guide/files
E
E                   Output of failed command:
E   Traceback (most recent call last):
E     File "/localdata/yis/workspace/poplar/popart/docs/user_guide/files/importing_session.py", line 19, in <module>
E       builder = popart.Builder("alexnet.onnx")
E     File "/localdata/yis/workspace/SDK/poplar_sdk-ubuntu_18_04-2.4.0+840-3f0821ff57/popart-ubuntu_18_04-2.4.0+2417-28149e3faf/python/popart/builder.py", line 43, in __init__
E       self._impl = _BuilderCore(modelProtoOrFilename)
E   RuntimeError: Your model ir_version is higher than the checker's.
___________________________________________________________________________________________________________________________________ TestPopartCustomOperatorCube.test_run_cube_custom_op ___________________________________________________________________________________________________________________________________

self = <test_examples.TestPopartCustomOperatorCube testMethod=test_run_cube_custom_op>

    def setUp(self):
        self.build_dir = os.path.join(self.base_path, "custom_op")
        self.run_command("make clean", self.build_dir, self.default_timeout)
>       self.run_command("make", self.build_dir, 600.0)

tests/test_examples.py:94:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/test_examples.py:40: in run_command
    Output of failed command:\n{combined_output}""")
E   AssertionError: The following command failed: make
E
E                   Working path: /localdata/yis/workspace/poplar/popart/docs/user_guide/files
E
E                   Output of failed command:
E   mkdir -p build
E   g++ custom_op.cpp  -lpopart -lpoplar -lpopops -std=c++11 -O3 -shared -fPIC -DONNX_NAMESPACE=onnx -o build/custom_op.so
E   custom_op.cpp:17:10: fatal error: onnx/defs/schema.h: No such file or directory
E    #include <onnx/defs/schema.h>
E             ^~~~~~~~~~~~~~~~~~~~
E   compilation terminated.
E   Makefile:18: recipe for target 'custom_op' failed
E   make: *** [custom_op] Error 1
================================================================================================================================================= short test summary info ==================================================================================================================================================
FAILED tests/test_examples.py::TestPythonDocExamples::test_documentation_import_session - AssertionError: The following command failed: /localdata/yis/workspace/SDK/poplar_sdk-ubuntu_18_04-2.4.0+840-3f0821ff57/2.4.0+840_poptorch/bin/python /localdata/yis/workspace/poplar/popart/docs/user_guide/files/importing_se...
FAILED tests/test_examples.py::TestPopartCustomOperatorCube::test_run_cube_custom_op - AssertionError: The following command failed: make
=============================================================================================================================================== 2 failed, 6 passed in 38.43s ===============================================================================================================================================
```

However, these error does not relate to the change applied.

Lint is skipped due to the following error:

```
  Error  () popart-test-linter
    Could not find `add_popart_py_unit_test` entry for 'test_examples.py' in
    'docs/user_guide/files/tests/CMakeLists.txt'. If this is intentional,
    please exclude the path "(docs/user_guide/files/tests/test_examples.py)"
    in the popart .arclint file, under the section 'popart-test-linter'.

 LINT ERRORS  Lint raised errors!
```

Reviewers: grahamh, jamiep, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, #popart, matthewha

Reviewed By: jamiep, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, #popart, matthewha

Subscribers: matthewha

Tags: #documentation_-_popart

Maniphest Tasks: T50050

Differential Revision: https://phabricator.sourcevertex.net/D57552